// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using practicing.Data;

#nullable disable

namespace practicing.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260126132334_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("practicing.Entity.Semester", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Semesters");
                });

            modelBuilder.Entity("practicing.Entity.Semester_Subject", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("semesterId")
                        .HasColumnType("int");

                    b.Property<int>("subjectId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("semesterId");

                    b.HasIndex("subjectId");

                    b.ToTable("Semester_Subjects");
                });

            modelBuilder.Entity("practicing.Entity.Student", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("semesterId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("semesterId");

                    b.ToTable("Students");
                });

            modelBuilder.Entity("practicing.Entity.Subject", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Subjects");
                });

            modelBuilder.Entity("practicing.Entity.Semester_Subject", b =>
                {
                    b.HasOne("practicing.Entity.Semester", "semester")
                        .WithMany("join")
                        .HasForeignKey("semesterId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("practicing.Entity.Subject", "subject")
                        .WithMany("Join")
                        .HasForeignKey("subjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("semester");

                    b.Navigation("subject");
                });

            modelBuilder.Entity("practicing.Entity.Student", b =>
                {
                    b.HasOne("practicing.Entity.Semester", "semester")
                        .WithMany("students")
                        .HasForeignKey("semesterId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("semester");
                });

            modelBuilder.Entity("practicing.Entity.Semester", b =>
                {
                    b.Navigation("join");

                    b.Navigation("students");
                });

            modelBuilder.Entity("practicing.Entity.Subject", b =>
                {
                    b.Navigation("Join");
                });
#pragma warning restore 612, 618
        }
    }
}
